server:
  port: 8086

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employeeDB
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: Pagination-demo

